import type { Payee } from "./payeeTypes";

//Action Types
export const CREATE_VERIFICATION_REQUEST = "CREATE_VERIFICATION_REQUEST";
export const CREATE_VERIFICATION_SUCCESS = "CREATE_VERIFICATION_SUCCESS";
export const CREATE_VERIFICATION_FAILURE = "CREATE_VERIFICATION_FAILURE";

export const FETCH_VERIFICATIONS_REQUEST = "FETCH_VERIFICATIONS_REQUEST";
export const FETCH_VERIFICATIONS_SUCCESS = "FETCH_VERIFICATIONS_SUCCESS";
export const FETCH_VERIFICATIONS_FAILURE = "FETCH_VERIFICATIONS_FAILURE";

export const FETCH_VERIFICATION_BY_ID_REQUEST =
  "FETCH_VERIFICATION_BY_ID_REQUEST";
export const FETCH_VERIFICATION_BY_ID_SUCCESS =
  "FETCH_VERIFICATION_BY_ID_SUCCESS";
export const FETCH_VERIFICATION_BY_ID_FAILURE =
  "FETCH_VERIFICATION_BY_ID_FAILURE";

export const SUBMIT_VERIFICATION_REQUEST = "SUBMIT_VERIFICATION_REQUEST";
export const SUBMIT_VERIFICATION_SUCCESS = "SUBMIT_VERIFICATION_SUCCESS";
export const SUBMIT_VERIFICATION_FAILURE = "SUBMIT_VERIFICATION_FAILURE";

export const DELETE_VERIFICATION_REQUEST = "DELETE_VERIFICATION_REQUEST";
export const DELETE_VERIFICATION_SUCCESS = "DELETE_VERIFICATION_SUCCESS";
export const DELETE_VERIFICATION_FAILURE = "DELETE_VERIFICATION_FAILURE";

export interface VerificationRecord {
  id: string;
  payee: Payee;
  coverage: string;
  copay: string;
  deductible: string;
  transcript: string;
  validity: string;
}
